# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
title: neueblog
description: blog for github and what have you
tagline: 
url: localhost:4000

# Used so Jekyll outputs the site correctly so Gulp can do what it wants
source: src
destination: serve

# Same as the title etc for your site but can instead be
# called by using 'site.owner.name' and so on
owner:
  name: Zaccary Price
  email: wildtangomedia@gmail.com
  bio: 
  twitter: wildtangoweb

# general setting for Jekyll
googleAnalytics: UA-XXXXX-X

# _config.build.yml overwrites these options when you run `gulp build`
# Enables future posts (posts with dates in the future) and drafts
future: true
show_drafts: true
# Disables the more accurate related posts for faster generating of the site
lsi: false
# Only make the last 10 posts so generating isn't slow
limit_posts: 10

# Permalink structure and pagination options
relative_permalinks: true
permalink: pretty
paginate: 4
paginate_path: 'page:num'

# Markdown library
markdown: redcarpet
# Markdown library options
# redcarpet:
  # extensions: ['fenced_code_blocks', 'smart']
pygments: true

excerpt_separator: <!--more-->
