# Run during the 'gulp build' command
# Overrides these options in the 

# Overrides the default URL, needed for your atom feed and sitemap
url: vivaldi-va.github.io

# Hides your drafts and future posts
future: false
show_drafts: false
# Gives you more accurate related posts
lsi: true
# Removes the upper limit for posts generated
limit_posts: 0

source: 'src'
destination: 'serve'